{
  "comments": [
    {
      "key": {
        "uuid": "57871979_983b5479",
        "filename": "components/pm-subscription-handler/pmsh_service/mod/api/services/subscription_service.py",
        "patchSetId": 11
      },
      "lineNbr": 431,
      "author": {
        "id": 7735
      },
      "writtenOn": "2022-03-01T13:58:43Z",
      "side": 1,
      "message": "I hope we need to rollback when some exception occurs in the below lines",
      "range": {
        "startLine": 428,
        "startChar": 4,
        "endLine": 431,
        "endChar": 23
      },
      "revId": "0970a3c59cc8753e5169f62d3ef299600eca9ef6",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "8eca7d2f_88f0c331",
        "filename": "components/pm-subscription-handler/pmsh_service/mod/api/services/subscription_service.py",
        "patchSetId": 11
      },
      "lineNbr": 456,
      "author": {
        "id": 4405
      },
      "writtenOn": "2022-03-01T13:57:46Z",
      "side": 1,
      "message": "This isn\u0027t really accurate.\nMaybe we need to rethink where we do the check for an empty list",
      "range": {
        "startLine": 456,
        "startChar": 26,
        "endLine": 456,
        "endChar": 44
      },
      "revId": "0970a3c59cc8753e5169f62d3ef299600eca9ef6",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": true
    }
  ]
}